// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BlockChain.proto

package grpcCode;

public final class BlockChainOuterClass {
  private BlockChainOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmptyMSGOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EmptyMSG)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code EmptyMSG}
   */
  public  static final class EmptyMSG extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:EmptyMSG)
      EmptyMSGOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EmptyMSG.newBuilder() to construct.
    private EmptyMSG(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EmptyMSG() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EmptyMSG(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpcCode.BlockChainOuterClass.internal_static_EmptyMSG_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpcCode.BlockChainOuterClass.internal_static_EmptyMSG_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpcCode.BlockChainOuterClass.EmptyMSG.class, grpcCode.BlockChainOuterClass.EmptyMSG.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpcCode.BlockChainOuterClass.EmptyMSG)) {
        return super.equals(obj);
      }
      grpcCode.BlockChainOuterClass.EmptyMSG other = (grpcCode.BlockChainOuterClass.EmptyMSG) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpcCode.BlockChainOuterClass.EmptyMSG parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpcCode.BlockChainOuterClass.EmptyMSG parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpcCode.BlockChainOuterClass.EmptyMSG parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpcCode.BlockChainOuterClass.EmptyMSG parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpcCode.BlockChainOuterClass.EmptyMSG parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpcCode.BlockChainOuterClass.EmptyMSG parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpcCode.BlockChainOuterClass.EmptyMSG parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpcCode.BlockChainOuterClass.EmptyMSG parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpcCode.BlockChainOuterClass.EmptyMSG parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpcCode.BlockChainOuterClass.EmptyMSG parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpcCode.BlockChainOuterClass.EmptyMSG parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpcCode.BlockChainOuterClass.EmptyMSG parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpcCode.BlockChainOuterClass.EmptyMSG prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EmptyMSG}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EmptyMSG)
        grpcCode.BlockChainOuterClass.EmptyMSGOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpcCode.BlockChainOuterClass.internal_static_EmptyMSG_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpcCode.BlockChainOuterClass.internal_static_EmptyMSG_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpcCode.BlockChainOuterClass.EmptyMSG.class, grpcCode.BlockChainOuterClass.EmptyMSG.Builder.class);
      }

      // Construct using grpcCode.BlockChainOuterClass.EmptyMSG.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpcCode.BlockChainOuterClass.internal_static_EmptyMSG_descriptor;
      }

      @java.lang.Override
      public grpcCode.BlockChainOuterClass.EmptyMSG getDefaultInstanceForType() {
        return grpcCode.BlockChainOuterClass.EmptyMSG.getDefaultInstance();
      }

      @java.lang.Override
      public grpcCode.BlockChainOuterClass.EmptyMSG build() {
        grpcCode.BlockChainOuterClass.EmptyMSG result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpcCode.BlockChainOuterClass.EmptyMSG buildPartial() {
        grpcCode.BlockChainOuterClass.EmptyMSG result = new grpcCode.BlockChainOuterClass.EmptyMSG(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpcCode.BlockChainOuterClass.EmptyMSG) {
          return mergeFrom((grpcCode.BlockChainOuterClass.EmptyMSG)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpcCode.BlockChainOuterClass.EmptyMSG other) {
        if (other == grpcCode.BlockChainOuterClass.EmptyMSG.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpcCode.BlockChainOuterClass.EmptyMSG parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpcCode.BlockChainOuterClass.EmptyMSG) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:EmptyMSG)
    }

    // @@protoc_insertion_point(class_scope:EmptyMSG)
    private static final grpcCode.BlockChainOuterClass.EmptyMSG DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpcCode.BlockChainOuterClass.EmptyMSG();
    }

    public static grpcCode.BlockChainOuterClass.EmptyMSG getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EmptyMSG>
        PARSER = new com.google.protobuf.AbstractParser<EmptyMSG>() {
      @java.lang.Override
      public EmptyMSG parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EmptyMSG(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EmptyMSG> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EmptyMSG> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpcCode.BlockChainOuterClass.EmptyMSG getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TransactionMSGOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TransactionMSG)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes sourceEntity = 1;</code>
     */
    com.google.protobuf.ByteString getSourceEntity();

    /**
     * <code>bytes destEntity = 2;</code>
     */
    com.google.protobuf.ByteString getDestEntity();

    /**
     * <code>bytes productId = 3;</code>
     */
    com.google.protobuf.ByteString getProductId();

    /**
     * <code>bytes bidTrans = 4;</code>
     */
    com.google.protobuf.ByteString getBidTrans();

    /**
     * <code>bytes signature = 5;</code>
     */
    com.google.protobuf.ByteString getSignature();
  }
  /**
   * Protobuf type {@code TransactionMSG}
   */
  public  static final class TransactionMSG extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TransactionMSG)
      TransactionMSGOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TransactionMSG.newBuilder() to construct.
    private TransactionMSG(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransactionMSG() {
      sourceEntity_ = com.google.protobuf.ByteString.EMPTY;
      destEntity_ = com.google.protobuf.ByteString.EMPTY;
      productId_ = com.google.protobuf.ByteString.EMPTY;
      bidTrans_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TransactionMSG(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              sourceEntity_ = input.readBytes();
              break;
            }
            case 18: {

              destEntity_ = input.readBytes();
              break;
            }
            case 26: {

              productId_ = input.readBytes();
              break;
            }
            case 34: {

              bidTrans_ = input.readBytes();
              break;
            }
            case 42: {

              signature_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpcCode.BlockChainOuterClass.internal_static_TransactionMSG_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpcCode.BlockChainOuterClass.internal_static_TransactionMSG_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpcCode.BlockChainOuterClass.TransactionMSG.class, grpcCode.BlockChainOuterClass.TransactionMSG.Builder.class);
    }

    public static final int SOURCEENTITY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString sourceEntity_;
    /**
     * <code>bytes sourceEntity = 1;</code>
     */
    public com.google.protobuf.ByteString getSourceEntity() {
      return sourceEntity_;
    }

    public static final int DESTENTITY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString destEntity_;
    /**
     * <code>bytes destEntity = 2;</code>
     */
    public com.google.protobuf.ByteString getDestEntity() {
      return destEntity_;
    }

    public static final int PRODUCTID_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString productId_;
    /**
     * <code>bytes productId = 3;</code>
     */
    public com.google.protobuf.ByteString getProductId() {
      return productId_;
    }

    public static final int BIDTRANS_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString bidTrans_;
    /**
     * <code>bytes bidTrans = 4;</code>
     */
    public com.google.protobuf.ByteString getBidTrans() {
      return bidTrans_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>bytes signature = 5;</code>
     */
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!sourceEntity_.isEmpty()) {
        output.writeBytes(1, sourceEntity_);
      }
      if (!destEntity_.isEmpty()) {
        output.writeBytes(2, destEntity_);
      }
      if (!productId_.isEmpty()) {
        output.writeBytes(3, productId_);
      }
      if (!bidTrans_.isEmpty()) {
        output.writeBytes(4, bidTrans_);
      }
      if (!signature_.isEmpty()) {
        output.writeBytes(5, signature_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!sourceEntity_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, sourceEntity_);
      }
      if (!destEntity_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, destEntity_);
      }
      if (!productId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, productId_);
      }
      if (!bidTrans_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, bidTrans_);
      }
      if (!signature_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, signature_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpcCode.BlockChainOuterClass.TransactionMSG)) {
        return super.equals(obj);
      }
      grpcCode.BlockChainOuterClass.TransactionMSG other = (grpcCode.BlockChainOuterClass.TransactionMSG) obj;

      boolean result = true;
      result = result && getSourceEntity()
          .equals(other.getSourceEntity());
      result = result && getDestEntity()
          .equals(other.getDestEntity());
      result = result && getProductId()
          .equals(other.getProductId());
      result = result && getBidTrans()
          .equals(other.getBidTrans());
      result = result && getSignature()
          .equals(other.getSignature());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SOURCEENTITY_FIELD_NUMBER;
      hash = (53 * hash) + getSourceEntity().hashCode();
      hash = (37 * hash) + DESTENTITY_FIELD_NUMBER;
      hash = (53 * hash) + getDestEntity().hashCode();
      hash = (37 * hash) + PRODUCTID_FIELD_NUMBER;
      hash = (53 * hash) + getProductId().hashCode();
      hash = (37 * hash) + BIDTRANS_FIELD_NUMBER;
      hash = (53 * hash) + getBidTrans().hashCode();
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpcCode.BlockChainOuterClass.TransactionMSG parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpcCode.BlockChainOuterClass.TransactionMSG parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpcCode.BlockChainOuterClass.TransactionMSG parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpcCode.BlockChainOuterClass.TransactionMSG parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpcCode.BlockChainOuterClass.TransactionMSG parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpcCode.BlockChainOuterClass.TransactionMSG parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpcCode.BlockChainOuterClass.TransactionMSG parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpcCode.BlockChainOuterClass.TransactionMSG parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpcCode.BlockChainOuterClass.TransactionMSG parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpcCode.BlockChainOuterClass.TransactionMSG parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpcCode.BlockChainOuterClass.TransactionMSG parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpcCode.BlockChainOuterClass.TransactionMSG parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpcCode.BlockChainOuterClass.TransactionMSG prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TransactionMSG}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TransactionMSG)
        grpcCode.BlockChainOuterClass.TransactionMSGOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpcCode.BlockChainOuterClass.internal_static_TransactionMSG_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpcCode.BlockChainOuterClass.internal_static_TransactionMSG_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpcCode.BlockChainOuterClass.TransactionMSG.class, grpcCode.BlockChainOuterClass.TransactionMSG.Builder.class);
      }

      // Construct using grpcCode.BlockChainOuterClass.TransactionMSG.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sourceEntity_ = com.google.protobuf.ByteString.EMPTY;

        destEntity_ = com.google.protobuf.ByteString.EMPTY;

        productId_ = com.google.protobuf.ByteString.EMPTY;

        bidTrans_ = com.google.protobuf.ByteString.EMPTY;

        signature_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpcCode.BlockChainOuterClass.internal_static_TransactionMSG_descriptor;
      }

      @java.lang.Override
      public grpcCode.BlockChainOuterClass.TransactionMSG getDefaultInstanceForType() {
        return grpcCode.BlockChainOuterClass.TransactionMSG.getDefaultInstance();
      }

      @java.lang.Override
      public grpcCode.BlockChainOuterClass.TransactionMSG build() {
        grpcCode.BlockChainOuterClass.TransactionMSG result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpcCode.BlockChainOuterClass.TransactionMSG buildPartial() {
        grpcCode.BlockChainOuterClass.TransactionMSG result = new grpcCode.BlockChainOuterClass.TransactionMSG(this);
        result.sourceEntity_ = sourceEntity_;
        result.destEntity_ = destEntity_;
        result.productId_ = productId_;
        result.bidTrans_ = bidTrans_;
        result.signature_ = signature_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpcCode.BlockChainOuterClass.TransactionMSG) {
          return mergeFrom((grpcCode.BlockChainOuterClass.TransactionMSG)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpcCode.BlockChainOuterClass.TransactionMSG other) {
        if (other == grpcCode.BlockChainOuterClass.TransactionMSG.getDefaultInstance()) return this;
        if (other.getSourceEntity() != com.google.protobuf.ByteString.EMPTY) {
          setSourceEntity(other.getSourceEntity());
        }
        if (other.getDestEntity() != com.google.protobuf.ByteString.EMPTY) {
          setDestEntity(other.getDestEntity());
        }
        if (other.getProductId() != com.google.protobuf.ByteString.EMPTY) {
          setProductId(other.getProductId());
        }
        if (other.getBidTrans() != com.google.protobuf.ByteString.EMPTY) {
          setBidTrans(other.getBidTrans());
        }
        if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
          setSignature(other.getSignature());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpcCode.BlockChainOuterClass.TransactionMSG parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpcCode.BlockChainOuterClass.TransactionMSG) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString sourceEntity_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes sourceEntity = 1;</code>
       */
      public com.google.protobuf.ByteString getSourceEntity() {
        return sourceEntity_;
      }
      /**
       * <code>bytes sourceEntity = 1;</code>
       */
      public Builder setSourceEntity(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sourceEntity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes sourceEntity = 1;</code>
       */
      public Builder clearSourceEntity() {
        
        sourceEntity_ = getDefaultInstance().getSourceEntity();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString destEntity_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes destEntity = 2;</code>
       */
      public com.google.protobuf.ByteString getDestEntity() {
        return destEntity_;
      }
      /**
       * <code>bytes destEntity = 2;</code>
       */
      public Builder setDestEntity(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        destEntity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes destEntity = 2;</code>
       */
      public Builder clearDestEntity() {
        
        destEntity_ = getDefaultInstance().getDestEntity();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString productId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes productId = 3;</code>
       */
      public com.google.protobuf.ByteString getProductId() {
        return productId_;
      }
      /**
       * <code>bytes productId = 3;</code>
       */
      public Builder setProductId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        productId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes productId = 3;</code>
       */
      public Builder clearProductId() {
        
        productId_ = getDefaultInstance().getProductId();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bidTrans_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes bidTrans = 4;</code>
       */
      public com.google.protobuf.ByteString getBidTrans() {
        return bidTrans_;
      }
      /**
       * <code>bytes bidTrans = 4;</code>
       */
      public Builder setBidTrans(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bidTrans_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes bidTrans = 4;</code>
       */
      public Builder clearBidTrans() {
        
        bidTrans_ = getDefaultInstance().getBidTrans();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes signature = 5;</code>
       */
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>bytes signature = 5;</code>
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes signature = 5;</code>
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TransactionMSG)
    }

    // @@protoc_insertion_point(class_scope:TransactionMSG)
    private static final grpcCode.BlockChainOuterClass.TransactionMSG DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpcCode.BlockChainOuterClass.TransactionMSG();
    }

    public static grpcCode.BlockChainOuterClass.TransactionMSG getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransactionMSG>
        PARSER = new com.google.protobuf.AbstractParser<TransactionMSG>() {
      @java.lang.Override
      public TransactionMSG parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransactionMSG(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransactionMSG> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransactionMSG> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpcCode.BlockChainOuterClass.TransactionMSG getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SuccessOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Success)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes success = 1;</code>
     */
    com.google.protobuf.ByteString getSuccess();

    /**
     * <code>bytes signature = 2;</code>
     */
    com.google.protobuf.ByteString getSignature();
  }
  /**
   * Protobuf type {@code Success}
   */
  public  static final class Success extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Success)
      SuccessOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Success.newBuilder() to construct.
    private Success(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Success() {
      success_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Success(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              success_ = input.readBytes();
              break;
            }
            case 18: {

              signature_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpcCode.BlockChainOuterClass.internal_static_Success_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpcCode.BlockChainOuterClass.internal_static_Success_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpcCode.BlockChainOuterClass.Success.class, grpcCode.BlockChainOuterClass.Success.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString success_;
    /**
     * <code>bytes success = 1;</code>
     */
    public com.google.protobuf.ByteString getSuccess() {
      return success_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>bytes signature = 2;</code>
     */
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!success_.isEmpty()) {
        output.writeBytes(1, success_);
      }
      if (!signature_.isEmpty()) {
        output.writeBytes(2, signature_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!success_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, success_);
      }
      if (!signature_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, signature_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpcCode.BlockChainOuterClass.Success)) {
        return super.equals(obj);
      }
      grpcCode.BlockChainOuterClass.Success other = (grpcCode.BlockChainOuterClass.Success) obj;

      boolean result = true;
      result = result && getSuccess()
          .equals(other.getSuccess());
      result = result && getSignature()
          .equals(other.getSignature());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + getSuccess().hashCode();
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpcCode.BlockChainOuterClass.Success parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpcCode.BlockChainOuterClass.Success parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpcCode.BlockChainOuterClass.Success parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpcCode.BlockChainOuterClass.Success parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpcCode.BlockChainOuterClass.Success parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpcCode.BlockChainOuterClass.Success parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpcCode.BlockChainOuterClass.Success parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpcCode.BlockChainOuterClass.Success parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpcCode.BlockChainOuterClass.Success parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpcCode.BlockChainOuterClass.Success parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpcCode.BlockChainOuterClass.Success parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpcCode.BlockChainOuterClass.Success parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpcCode.BlockChainOuterClass.Success prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Success}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Success)
        grpcCode.BlockChainOuterClass.SuccessOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpcCode.BlockChainOuterClass.internal_static_Success_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpcCode.BlockChainOuterClass.internal_static_Success_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpcCode.BlockChainOuterClass.Success.class, grpcCode.BlockChainOuterClass.Success.Builder.class);
      }

      // Construct using grpcCode.BlockChainOuterClass.Success.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        success_ = com.google.protobuf.ByteString.EMPTY;

        signature_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpcCode.BlockChainOuterClass.internal_static_Success_descriptor;
      }

      @java.lang.Override
      public grpcCode.BlockChainOuterClass.Success getDefaultInstanceForType() {
        return grpcCode.BlockChainOuterClass.Success.getDefaultInstance();
      }

      @java.lang.Override
      public grpcCode.BlockChainOuterClass.Success build() {
        grpcCode.BlockChainOuterClass.Success result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpcCode.BlockChainOuterClass.Success buildPartial() {
        grpcCode.BlockChainOuterClass.Success result = new grpcCode.BlockChainOuterClass.Success(this);
        result.success_ = success_;
        result.signature_ = signature_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpcCode.BlockChainOuterClass.Success) {
          return mergeFrom((grpcCode.BlockChainOuterClass.Success)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpcCode.BlockChainOuterClass.Success other) {
        if (other == grpcCode.BlockChainOuterClass.Success.getDefaultInstance()) return this;
        if (other.getSuccess() != com.google.protobuf.ByteString.EMPTY) {
          setSuccess(other.getSuccess());
        }
        if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
          setSignature(other.getSignature());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpcCode.BlockChainOuterClass.Success parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpcCode.BlockChainOuterClass.Success) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString success_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes success = 1;</code>
       */
      public com.google.protobuf.ByteString getSuccess() {
        return success_;
      }
      /**
       * <code>bytes success = 1;</code>
       */
      public Builder setSuccess(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes success = 1;</code>
       */
      public Builder clearSuccess() {
        
        success_ = getDefaultInstance().getSuccess();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes signature = 2;</code>
       */
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>bytes signature = 2;</code>
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes signature = 2;</code>
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Success)
    }

    // @@protoc_insertion_point(class_scope:Success)
    private static final grpcCode.BlockChainOuterClass.Success DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpcCode.BlockChainOuterClass.Success();
    }

    public static grpcCode.BlockChainOuterClass.Success getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Success>
        PARSER = new com.google.protobuf.AbstractParser<Success>() {
      @java.lang.Override
      public Success parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Success(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Success> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Success> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpcCode.BlockChainOuterClass.Success getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmptyMSG_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmptyMSG_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransactionMSG_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransactionMSG_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Success_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Success_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020BlockChain.proto\"\n\n\010EmptyMSG\"r\n\016Transa" +
      "ctionMSG\022\024\n\014sourceEntity\030\001 \001(\014\022\022\n\ndestEn" +
      "tity\030\002 \001(\014\022\021\n\tproductId\030\003 \001(\014\022\020\n\010bidTran" +
      "s\030\004 \001(\014\022\021\n\tsignature\030\005 \001(\014\"-\n\007Success\022\017\n" +
      "\007success\030\001 \001(\014\022\021\n\tsignature\030\002 \001(\0142<\n\nBlo" +
      "ckChain\022.\n\017SendTransaction\022\017.Transaction" +
      "MSG\032\010.Success\"\000B\n\n\010grpcCodeb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_EmptyMSG_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EmptyMSG_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmptyMSG_descriptor,
        new java.lang.String[] { });
    internal_static_TransactionMSG_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TransactionMSG_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransactionMSG_descriptor,
        new java.lang.String[] { "SourceEntity", "DestEntity", "ProductId", "BidTrans", "Signature", });
    internal_static_Success_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Success_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Success_descriptor,
        new java.lang.String[] { "Success", "Signature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
