// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PeerToPeer.proto

package grpcCode;

public final class PeerToPeerOuterClass {
  private PeerToPeerOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PingInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PingInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.NodeInfo dest = 1;</code>
     */
    boolean hasDest();
    /**
     * <code>.NodeInfo dest = 1;</code>
     */
    grpcCode.PeerToPeerOuterClass.NodeInfo getDest();
    /**
     * <code>.NodeInfo dest = 1;</code>
     */
    grpcCode.PeerToPeerOuterClass.NodeInfoOrBuilder getDestOrBuilder();

    /**
     * <code>.NodeInfo orig = 2;</code>
     */
    boolean hasOrig();
    /**
     * <code>.NodeInfo orig = 2;</code>
     */
    grpcCode.PeerToPeerOuterClass.NodeInfo getOrig();
    /**
     * <code>.NodeInfo orig = 2;</code>
     */
    grpcCode.PeerToPeerOuterClass.NodeInfoOrBuilder getOrigOrBuilder();
  }
  /**
   * Protobuf type {@code PingInfo}
   */
  public  static final class PingInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PingInfo)
      PingInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PingInfo.newBuilder() to construct.
    private PingInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PingInfo() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PingInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              grpcCode.PeerToPeerOuterClass.NodeInfo.Builder subBuilder = null;
              if (dest_ != null) {
                subBuilder = dest_.toBuilder();
              }
              dest_ = input.readMessage(grpcCode.PeerToPeerOuterClass.NodeInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(dest_);
                dest_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              grpcCode.PeerToPeerOuterClass.NodeInfo.Builder subBuilder = null;
              if (orig_ != null) {
                subBuilder = orig_.toBuilder();
              }
              orig_ = input.readMessage(grpcCode.PeerToPeerOuterClass.NodeInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(orig_);
                orig_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpcCode.PeerToPeerOuterClass.internal_static_PingInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpcCode.PeerToPeerOuterClass.internal_static_PingInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpcCode.PeerToPeerOuterClass.PingInfo.class, grpcCode.PeerToPeerOuterClass.PingInfo.Builder.class);
    }

    public static final int DEST_FIELD_NUMBER = 1;
    private grpcCode.PeerToPeerOuterClass.NodeInfo dest_;
    /**
     * <code>.NodeInfo dest = 1;</code>
     */
    public boolean hasDest() {
      return dest_ != null;
    }
    /**
     * <code>.NodeInfo dest = 1;</code>
     */
    public grpcCode.PeerToPeerOuterClass.NodeInfo getDest() {
      return dest_ == null ? grpcCode.PeerToPeerOuterClass.NodeInfo.getDefaultInstance() : dest_;
    }
    /**
     * <code>.NodeInfo dest = 1;</code>
     */
    public grpcCode.PeerToPeerOuterClass.NodeInfoOrBuilder getDestOrBuilder() {
      return getDest();
    }

    public static final int ORIG_FIELD_NUMBER = 2;
    private grpcCode.PeerToPeerOuterClass.NodeInfo orig_;
    /**
     * <code>.NodeInfo orig = 2;</code>
     */
    public boolean hasOrig() {
      return orig_ != null;
    }
    /**
     * <code>.NodeInfo orig = 2;</code>
     */
    public grpcCode.PeerToPeerOuterClass.NodeInfo getOrig() {
      return orig_ == null ? grpcCode.PeerToPeerOuterClass.NodeInfo.getDefaultInstance() : orig_;
    }
    /**
     * <code>.NodeInfo orig = 2;</code>
     */
    public grpcCode.PeerToPeerOuterClass.NodeInfoOrBuilder getOrigOrBuilder() {
      return getOrig();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dest_ != null) {
        output.writeMessage(1, getDest());
      }
      if (orig_ != null) {
        output.writeMessage(2, getOrig());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dest_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getDest());
      }
      if (orig_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getOrig());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpcCode.PeerToPeerOuterClass.PingInfo)) {
        return super.equals(obj);
      }
      grpcCode.PeerToPeerOuterClass.PingInfo other = (grpcCode.PeerToPeerOuterClass.PingInfo) obj;

      boolean result = true;
      result = result && (hasDest() == other.hasDest());
      if (hasDest()) {
        result = result && getDest()
            .equals(other.getDest());
      }
      result = result && (hasOrig() == other.hasOrig());
      if (hasOrig()) {
        result = result && getOrig()
            .equals(other.getOrig());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDest()) {
        hash = (37 * hash) + DEST_FIELD_NUMBER;
        hash = (53 * hash) + getDest().hashCode();
      }
      if (hasOrig()) {
        hash = (37 * hash) + ORIG_FIELD_NUMBER;
        hash = (53 * hash) + getOrig().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpcCode.PeerToPeerOuterClass.PingInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpcCode.PeerToPeerOuterClass.PingInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpcCode.PeerToPeerOuterClass.PingInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpcCode.PeerToPeerOuterClass.PingInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpcCode.PeerToPeerOuterClass.PingInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpcCode.PeerToPeerOuterClass.PingInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpcCode.PeerToPeerOuterClass.PingInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpcCode.PeerToPeerOuterClass.PingInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpcCode.PeerToPeerOuterClass.PingInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpcCode.PeerToPeerOuterClass.PingInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpcCode.PeerToPeerOuterClass.PingInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpcCode.PeerToPeerOuterClass.PingInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpcCode.PeerToPeerOuterClass.PingInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PingInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PingInfo)
        grpcCode.PeerToPeerOuterClass.PingInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpcCode.PeerToPeerOuterClass.internal_static_PingInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpcCode.PeerToPeerOuterClass.internal_static_PingInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpcCode.PeerToPeerOuterClass.PingInfo.class, grpcCode.PeerToPeerOuterClass.PingInfo.Builder.class);
      }

      // Construct using grpcCode.PeerToPeerOuterClass.PingInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (destBuilder_ == null) {
          dest_ = null;
        } else {
          dest_ = null;
          destBuilder_ = null;
        }
        if (origBuilder_ == null) {
          orig_ = null;
        } else {
          orig_ = null;
          origBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpcCode.PeerToPeerOuterClass.internal_static_PingInfo_descriptor;
      }

      @java.lang.Override
      public grpcCode.PeerToPeerOuterClass.PingInfo getDefaultInstanceForType() {
        return grpcCode.PeerToPeerOuterClass.PingInfo.getDefaultInstance();
      }

      @java.lang.Override
      public grpcCode.PeerToPeerOuterClass.PingInfo build() {
        grpcCode.PeerToPeerOuterClass.PingInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpcCode.PeerToPeerOuterClass.PingInfo buildPartial() {
        grpcCode.PeerToPeerOuterClass.PingInfo result = new grpcCode.PeerToPeerOuterClass.PingInfo(this);
        if (destBuilder_ == null) {
          result.dest_ = dest_;
        } else {
          result.dest_ = destBuilder_.build();
        }
        if (origBuilder_ == null) {
          result.orig_ = orig_;
        } else {
          result.orig_ = origBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpcCode.PeerToPeerOuterClass.PingInfo) {
          return mergeFrom((grpcCode.PeerToPeerOuterClass.PingInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpcCode.PeerToPeerOuterClass.PingInfo other) {
        if (other == grpcCode.PeerToPeerOuterClass.PingInfo.getDefaultInstance()) return this;
        if (other.hasDest()) {
          mergeDest(other.getDest());
        }
        if (other.hasOrig()) {
          mergeOrig(other.getOrig());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpcCode.PeerToPeerOuterClass.PingInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpcCode.PeerToPeerOuterClass.PingInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private grpcCode.PeerToPeerOuterClass.NodeInfo dest_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          grpcCode.PeerToPeerOuterClass.NodeInfo, grpcCode.PeerToPeerOuterClass.NodeInfo.Builder, grpcCode.PeerToPeerOuterClass.NodeInfoOrBuilder> destBuilder_;
      /**
       * <code>.NodeInfo dest = 1;</code>
       */
      public boolean hasDest() {
        return destBuilder_ != null || dest_ != null;
      }
      /**
       * <code>.NodeInfo dest = 1;</code>
       */
      public grpcCode.PeerToPeerOuterClass.NodeInfo getDest() {
        if (destBuilder_ == null) {
          return dest_ == null ? grpcCode.PeerToPeerOuterClass.NodeInfo.getDefaultInstance() : dest_;
        } else {
          return destBuilder_.getMessage();
        }
      }
      /**
       * <code>.NodeInfo dest = 1;</code>
       */
      public Builder setDest(grpcCode.PeerToPeerOuterClass.NodeInfo value) {
        if (destBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dest_ = value;
          onChanged();
        } else {
          destBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.NodeInfo dest = 1;</code>
       */
      public Builder setDest(
          grpcCode.PeerToPeerOuterClass.NodeInfo.Builder builderForValue) {
        if (destBuilder_ == null) {
          dest_ = builderForValue.build();
          onChanged();
        } else {
          destBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.NodeInfo dest = 1;</code>
       */
      public Builder mergeDest(grpcCode.PeerToPeerOuterClass.NodeInfo value) {
        if (destBuilder_ == null) {
          if (dest_ != null) {
            dest_ =
              grpcCode.PeerToPeerOuterClass.NodeInfo.newBuilder(dest_).mergeFrom(value).buildPartial();
          } else {
            dest_ = value;
          }
          onChanged();
        } else {
          destBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.NodeInfo dest = 1;</code>
       */
      public Builder clearDest() {
        if (destBuilder_ == null) {
          dest_ = null;
          onChanged();
        } else {
          dest_ = null;
          destBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.NodeInfo dest = 1;</code>
       */
      public grpcCode.PeerToPeerOuterClass.NodeInfo.Builder getDestBuilder() {
        
        onChanged();
        return getDestFieldBuilder().getBuilder();
      }
      /**
       * <code>.NodeInfo dest = 1;</code>
       */
      public grpcCode.PeerToPeerOuterClass.NodeInfoOrBuilder getDestOrBuilder() {
        if (destBuilder_ != null) {
          return destBuilder_.getMessageOrBuilder();
        } else {
          return dest_ == null ?
              grpcCode.PeerToPeerOuterClass.NodeInfo.getDefaultInstance() : dest_;
        }
      }
      /**
       * <code>.NodeInfo dest = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          grpcCode.PeerToPeerOuterClass.NodeInfo, grpcCode.PeerToPeerOuterClass.NodeInfo.Builder, grpcCode.PeerToPeerOuterClass.NodeInfoOrBuilder> 
          getDestFieldBuilder() {
        if (destBuilder_ == null) {
          destBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              grpcCode.PeerToPeerOuterClass.NodeInfo, grpcCode.PeerToPeerOuterClass.NodeInfo.Builder, grpcCode.PeerToPeerOuterClass.NodeInfoOrBuilder>(
                  getDest(),
                  getParentForChildren(),
                  isClean());
          dest_ = null;
        }
        return destBuilder_;
      }

      private grpcCode.PeerToPeerOuterClass.NodeInfo orig_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          grpcCode.PeerToPeerOuterClass.NodeInfo, grpcCode.PeerToPeerOuterClass.NodeInfo.Builder, grpcCode.PeerToPeerOuterClass.NodeInfoOrBuilder> origBuilder_;
      /**
       * <code>.NodeInfo orig = 2;</code>
       */
      public boolean hasOrig() {
        return origBuilder_ != null || orig_ != null;
      }
      /**
       * <code>.NodeInfo orig = 2;</code>
       */
      public grpcCode.PeerToPeerOuterClass.NodeInfo getOrig() {
        if (origBuilder_ == null) {
          return orig_ == null ? grpcCode.PeerToPeerOuterClass.NodeInfo.getDefaultInstance() : orig_;
        } else {
          return origBuilder_.getMessage();
        }
      }
      /**
       * <code>.NodeInfo orig = 2;</code>
       */
      public Builder setOrig(grpcCode.PeerToPeerOuterClass.NodeInfo value) {
        if (origBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          orig_ = value;
          onChanged();
        } else {
          origBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.NodeInfo orig = 2;</code>
       */
      public Builder setOrig(
          grpcCode.PeerToPeerOuterClass.NodeInfo.Builder builderForValue) {
        if (origBuilder_ == null) {
          orig_ = builderForValue.build();
          onChanged();
        } else {
          origBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.NodeInfo orig = 2;</code>
       */
      public Builder mergeOrig(grpcCode.PeerToPeerOuterClass.NodeInfo value) {
        if (origBuilder_ == null) {
          if (orig_ != null) {
            orig_ =
              grpcCode.PeerToPeerOuterClass.NodeInfo.newBuilder(orig_).mergeFrom(value).buildPartial();
          } else {
            orig_ = value;
          }
          onChanged();
        } else {
          origBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.NodeInfo orig = 2;</code>
       */
      public Builder clearOrig() {
        if (origBuilder_ == null) {
          orig_ = null;
          onChanged();
        } else {
          orig_ = null;
          origBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.NodeInfo orig = 2;</code>
       */
      public grpcCode.PeerToPeerOuterClass.NodeInfo.Builder getOrigBuilder() {
        
        onChanged();
        return getOrigFieldBuilder().getBuilder();
      }
      /**
       * <code>.NodeInfo orig = 2;</code>
       */
      public grpcCode.PeerToPeerOuterClass.NodeInfoOrBuilder getOrigOrBuilder() {
        if (origBuilder_ != null) {
          return origBuilder_.getMessageOrBuilder();
        } else {
          return orig_ == null ?
              grpcCode.PeerToPeerOuterClass.NodeInfo.getDefaultInstance() : orig_;
        }
      }
      /**
       * <code>.NodeInfo orig = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          grpcCode.PeerToPeerOuterClass.NodeInfo, grpcCode.PeerToPeerOuterClass.NodeInfo.Builder, grpcCode.PeerToPeerOuterClass.NodeInfoOrBuilder> 
          getOrigFieldBuilder() {
        if (origBuilder_ == null) {
          origBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              grpcCode.PeerToPeerOuterClass.NodeInfo, grpcCode.PeerToPeerOuterClass.NodeInfo.Builder, grpcCode.PeerToPeerOuterClass.NodeInfoOrBuilder>(
                  getOrig(),
                  getParentForChildren(),
                  isClean());
          orig_ = null;
        }
        return origBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PingInfo)
    }

    // @@protoc_insertion_point(class_scope:PingInfo)
    private static final grpcCode.PeerToPeerOuterClass.PingInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpcCode.PeerToPeerOuterClass.PingInfo();
    }

    public static grpcCode.PeerToPeerOuterClass.PingInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PingInfo>
        PARSER = new com.google.protobuf.AbstractParser<PingInfo>() {
      @java.lang.Override
      public PingInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PingInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PingInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PingInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpcCode.PeerToPeerOuterClass.PingInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NodeInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NodeInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Node identification
     * </pre>
     *
     * <code>bytes nodeId = 1;</code>
     */
    com.google.protobuf.ByteString getNodeId();

    /**
     * <pre>
     * IP of node
     * </pre>
     *
     * <code>string nodeIp = 2;</code>
     */
    java.lang.String getNodeIp();
    /**
     * <pre>
     * IP of node
     * </pre>
     *
     * <code>string nodeIp = 2;</code>
     */
    com.google.protobuf.ByteString
        getNodeIpBytes();

    /**
     * <pre>
     * Port of the node
     * </pre>
     *
     * <code>int32 nodePort = 3;</code>
     */
    int getNodePort();
  }
  /**
   * <pre>
   **
   *Message format for a basic info of a node
   * </pre>
   *
   * Protobuf type {@code NodeInfo}
   */
  public  static final class NodeInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NodeInfo)
      NodeInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NodeInfo.newBuilder() to construct.
    private NodeInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NodeInfo() {
      nodeId_ = com.google.protobuf.ByteString.EMPTY;
      nodeIp_ = "";
      nodePort_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NodeInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              nodeId_ = input.readBytes();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              nodeIp_ = s;
              break;
            }
            case 24: {

              nodePort_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpcCode.PeerToPeerOuterClass.internal_static_NodeInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpcCode.PeerToPeerOuterClass.internal_static_NodeInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpcCode.PeerToPeerOuterClass.NodeInfo.class, grpcCode.PeerToPeerOuterClass.NodeInfo.Builder.class);
    }

    public static final int NODEID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString nodeId_;
    /**
     * <pre>
     * Node identification
     * </pre>
     *
     * <code>bytes nodeId = 1;</code>
     */
    public com.google.protobuf.ByteString getNodeId() {
      return nodeId_;
    }

    public static final int NODEIP_FIELD_NUMBER = 2;
    private volatile java.lang.Object nodeIp_;
    /**
     * <pre>
     * IP of node
     * </pre>
     *
     * <code>string nodeIp = 2;</code>
     */
    public java.lang.String getNodeIp() {
      java.lang.Object ref = nodeIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeIp_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * IP of node
     * </pre>
     *
     * <code>string nodeIp = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNodeIpBytes() {
      java.lang.Object ref = nodeIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NODEPORT_FIELD_NUMBER = 3;
    private int nodePort_;
    /**
     * <pre>
     * Port of the node
     * </pre>
     *
     * <code>int32 nodePort = 3;</code>
     */
    public int getNodePort() {
      return nodePort_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!nodeId_.isEmpty()) {
        output.writeBytes(1, nodeId_);
      }
      if (!getNodeIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nodeIp_);
      }
      if (nodePort_ != 0) {
        output.writeInt32(3, nodePort_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!nodeId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, nodeId_);
      }
      if (!getNodeIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nodeIp_);
      }
      if (nodePort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, nodePort_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpcCode.PeerToPeerOuterClass.NodeInfo)) {
        return super.equals(obj);
      }
      grpcCode.PeerToPeerOuterClass.NodeInfo other = (grpcCode.PeerToPeerOuterClass.NodeInfo) obj;

      boolean result = true;
      result = result && getNodeId()
          .equals(other.getNodeId());
      result = result && getNodeIp()
          .equals(other.getNodeIp());
      result = result && (getNodePort()
          == other.getNodePort());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NODEID_FIELD_NUMBER;
      hash = (53 * hash) + getNodeId().hashCode();
      hash = (37 * hash) + NODEIP_FIELD_NUMBER;
      hash = (53 * hash) + getNodeIp().hashCode();
      hash = (37 * hash) + NODEPORT_FIELD_NUMBER;
      hash = (53 * hash) + getNodePort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpcCode.PeerToPeerOuterClass.NodeInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpcCode.PeerToPeerOuterClass.NodeInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpcCode.PeerToPeerOuterClass.NodeInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpcCode.PeerToPeerOuterClass.NodeInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpcCode.PeerToPeerOuterClass.NodeInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpcCode.PeerToPeerOuterClass.NodeInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpcCode.PeerToPeerOuterClass.NodeInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpcCode.PeerToPeerOuterClass.NodeInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpcCode.PeerToPeerOuterClass.NodeInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpcCode.PeerToPeerOuterClass.NodeInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpcCode.PeerToPeerOuterClass.NodeInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpcCode.PeerToPeerOuterClass.NodeInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpcCode.PeerToPeerOuterClass.NodeInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     *Message format for a basic info of a node
     * </pre>
     *
     * Protobuf type {@code NodeInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NodeInfo)
        grpcCode.PeerToPeerOuterClass.NodeInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpcCode.PeerToPeerOuterClass.internal_static_NodeInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpcCode.PeerToPeerOuterClass.internal_static_NodeInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpcCode.PeerToPeerOuterClass.NodeInfo.class, grpcCode.PeerToPeerOuterClass.NodeInfo.Builder.class);
      }

      // Construct using grpcCode.PeerToPeerOuterClass.NodeInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nodeId_ = com.google.protobuf.ByteString.EMPTY;

        nodeIp_ = "";

        nodePort_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpcCode.PeerToPeerOuterClass.internal_static_NodeInfo_descriptor;
      }

      @java.lang.Override
      public grpcCode.PeerToPeerOuterClass.NodeInfo getDefaultInstanceForType() {
        return grpcCode.PeerToPeerOuterClass.NodeInfo.getDefaultInstance();
      }

      @java.lang.Override
      public grpcCode.PeerToPeerOuterClass.NodeInfo build() {
        grpcCode.PeerToPeerOuterClass.NodeInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpcCode.PeerToPeerOuterClass.NodeInfo buildPartial() {
        grpcCode.PeerToPeerOuterClass.NodeInfo result = new grpcCode.PeerToPeerOuterClass.NodeInfo(this);
        result.nodeId_ = nodeId_;
        result.nodeIp_ = nodeIp_;
        result.nodePort_ = nodePort_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpcCode.PeerToPeerOuterClass.NodeInfo) {
          return mergeFrom((grpcCode.PeerToPeerOuterClass.NodeInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpcCode.PeerToPeerOuterClass.NodeInfo other) {
        if (other == grpcCode.PeerToPeerOuterClass.NodeInfo.getDefaultInstance()) return this;
        if (other.getNodeId() != com.google.protobuf.ByteString.EMPTY) {
          setNodeId(other.getNodeId());
        }
        if (!other.getNodeIp().isEmpty()) {
          nodeIp_ = other.nodeIp_;
          onChanged();
        }
        if (other.getNodePort() != 0) {
          setNodePort(other.getNodePort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpcCode.PeerToPeerOuterClass.NodeInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpcCode.PeerToPeerOuterClass.NodeInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString nodeId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Node identification
       * </pre>
       *
       * <code>bytes nodeId = 1;</code>
       */
      public com.google.protobuf.ByteString getNodeId() {
        return nodeId_;
      }
      /**
       * <pre>
       * Node identification
       * </pre>
       *
       * <code>bytes nodeId = 1;</code>
       */
      public Builder setNodeId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Node identification
       * </pre>
       *
       * <code>bytes nodeId = 1;</code>
       */
      public Builder clearNodeId() {
        
        nodeId_ = getDefaultInstance().getNodeId();
        onChanged();
        return this;
      }

      private java.lang.Object nodeIp_ = "";
      /**
       * <pre>
       * IP of node
       * </pre>
       *
       * <code>string nodeIp = 2;</code>
       */
      public java.lang.String getNodeIp() {
        java.lang.Object ref = nodeIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nodeIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * IP of node
       * </pre>
       *
       * <code>string nodeIp = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNodeIpBytes() {
        java.lang.Object ref = nodeIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * IP of node
       * </pre>
       *
       * <code>string nodeIp = 2;</code>
       */
      public Builder setNodeIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nodeIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * IP of node
       * </pre>
       *
       * <code>string nodeIp = 2;</code>
       */
      public Builder clearNodeIp() {
        
        nodeIp_ = getDefaultInstance().getNodeIp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * IP of node
       * </pre>
       *
       * <code>string nodeIp = 2;</code>
       */
      public Builder setNodeIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nodeIp_ = value;
        onChanged();
        return this;
      }

      private int nodePort_ ;
      /**
       * <pre>
       * Port of the node
       * </pre>
       *
       * <code>int32 nodePort = 3;</code>
       */
      public int getNodePort() {
        return nodePort_;
      }
      /**
       * <pre>
       * Port of the node
       * </pre>
       *
       * <code>int32 nodePort = 3;</code>
       */
      public Builder setNodePort(int value) {
        
        nodePort_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Port of the node
       * </pre>
       *
       * <code>int32 nodePort = 3;</code>
       */
      public Builder clearNodePort() {
        
        nodePort_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NodeInfo)
    }

    // @@protoc_insertion_point(class_scope:NodeInfo)
    private static final grpcCode.PeerToPeerOuterClass.NodeInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpcCode.PeerToPeerOuterClass.NodeInfo();
    }

    public static grpcCode.PeerToPeerOuterClass.NodeInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NodeInfo>
        PARSER = new com.google.protobuf.AbstractParser<NodeInfo>() {
      @java.lang.Override
      public NodeInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NodeInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NodeInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NodeInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpcCode.PeerToPeerOuterClass.NodeInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PingSuccessOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PingSuccess)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * True if ping was received, otherwise false
     * </pre>
     *
     * <code>bool success = 1;</code>
     */
    boolean getSuccess();
  }
  /**
   * <pre>
   **
   *Message format for a ping response
   * </pre>
   *
   * Protobuf type {@code PingSuccess}
   */
  public  static final class PingSuccess extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PingSuccess)
      PingSuccessOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PingSuccess.newBuilder() to construct.
    private PingSuccess(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PingSuccess() {
      success_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PingSuccess(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              success_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpcCode.PeerToPeerOuterClass.internal_static_PingSuccess_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpcCode.PeerToPeerOuterClass.internal_static_PingSuccess_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpcCode.PeerToPeerOuterClass.PingSuccess.class, grpcCode.PeerToPeerOuterClass.PingSuccess.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <pre>
     * True if ping was received, otherwise false
     * </pre>
     *
     * <code>bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpcCode.PeerToPeerOuterClass.PingSuccess)) {
        return super.equals(obj);
      }
      grpcCode.PeerToPeerOuterClass.PingSuccess other = (grpcCode.PeerToPeerOuterClass.PingSuccess) obj;

      boolean result = true;
      result = result && (getSuccess()
          == other.getSuccess());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpcCode.PeerToPeerOuterClass.PingSuccess parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpcCode.PeerToPeerOuterClass.PingSuccess parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpcCode.PeerToPeerOuterClass.PingSuccess parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpcCode.PeerToPeerOuterClass.PingSuccess parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpcCode.PeerToPeerOuterClass.PingSuccess parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpcCode.PeerToPeerOuterClass.PingSuccess parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpcCode.PeerToPeerOuterClass.PingSuccess parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpcCode.PeerToPeerOuterClass.PingSuccess parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpcCode.PeerToPeerOuterClass.PingSuccess parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpcCode.PeerToPeerOuterClass.PingSuccess parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpcCode.PeerToPeerOuterClass.PingSuccess parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpcCode.PeerToPeerOuterClass.PingSuccess parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpcCode.PeerToPeerOuterClass.PingSuccess prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     *Message format for a ping response
     * </pre>
     *
     * Protobuf type {@code PingSuccess}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PingSuccess)
        grpcCode.PeerToPeerOuterClass.PingSuccessOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpcCode.PeerToPeerOuterClass.internal_static_PingSuccess_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpcCode.PeerToPeerOuterClass.internal_static_PingSuccess_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpcCode.PeerToPeerOuterClass.PingSuccess.class, grpcCode.PeerToPeerOuterClass.PingSuccess.Builder.class);
      }

      // Construct using grpcCode.PeerToPeerOuterClass.PingSuccess.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        success_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpcCode.PeerToPeerOuterClass.internal_static_PingSuccess_descriptor;
      }

      @java.lang.Override
      public grpcCode.PeerToPeerOuterClass.PingSuccess getDefaultInstanceForType() {
        return grpcCode.PeerToPeerOuterClass.PingSuccess.getDefaultInstance();
      }

      @java.lang.Override
      public grpcCode.PeerToPeerOuterClass.PingSuccess build() {
        grpcCode.PeerToPeerOuterClass.PingSuccess result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpcCode.PeerToPeerOuterClass.PingSuccess buildPartial() {
        grpcCode.PeerToPeerOuterClass.PingSuccess result = new grpcCode.PeerToPeerOuterClass.PingSuccess(this);
        result.success_ = success_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpcCode.PeerToPeerOuterClass.PingSuccess) {
          return mergeFrom((grpcCode.PeerToPeerOuterClass.PingSuccess)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpcCode.PeerToPeerOuterClass.PingSuccess other) {
        if (other == grpcCode.PeerToPeerOuterClass.PingSuccess.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpcCode.PeerToPeerOuterClass.PingSuccess parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpcCode.PeerToPeerOuterClass.PingSuccess) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean success_ ;
      /**
       * <pre>
       * True if ping was received, otherwise false
       * </pre>
       *
       * <code>bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <pre>
       * True if ping was received, otherwise false
       * </pre>
       *
       * <code>bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * True if ping was received, otherwise false
       * </pre>
       *
       * <code>bool success = 1;</code>
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PingSuccess)
    }

    // @@protoc_insertion_point(class_scope:PingSuccess)
    private static final grpcCode.PeerToPeerOuterClass.PingSuccess DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpcCode.PeerToPeerOuterClass.PingSuccess();
    }

    public static grpcCode.PeerToPeerOuterClass.PingSuccess getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PingSuccess>
        PARSER = new com.google.protobuf.AbstractParser<PingSuccess>() {
      @java.lang.Override
      public PingSuccess parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PingSuccess(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PingSuccess> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PingSuccess> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpcCode.PeerToPeerOuterClass.PingSuccess getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PingInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PingInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NodeInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NodeInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PingSuccess_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PingSuccess_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020PeerToPeer.proto\"<\n\010PingInfo\022\027\n\004dest\030\001" +
      " \001(\0132\t.NodeInfo\022\027\n\004orig\030\002 \001(\0132\t.NodeInfo" +
      "\"<\n\010NodeInfo\022\016\n\006nodeId\030\001 \001(\014\022\016\n\006nodeIp\030\002" +
      " \001(\t\022\020\n\010nodePort\030\003 \001(\005\"\036\n\013PingSuccess\022\017\n" +
      "\007success\030\001 \001(\0102/\n\nPeerToPeer\022!\n\004Ping\022\t.P" +
      "ingInfo\032\014.PingSuccess\"\000B\n\n\010grpcCodeb\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PingInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PingInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PingInfo_descriptor,
        new java.lang.String[] { "Dest", "Orig", });
    internal_static_NodeInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_NodeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NodeInfo_descriptor,
        new java.lang.String[] { "NodeId", "NodeIp", "NodePort", });
    internal_static_PingSuccess_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PingSuccess_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PingSuccess_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
